
services:
  - type: web
    name: graph-proxy
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host=0.0.0.0 --port=10000
    envVars:
      - key: CLIENT_ID
        value: "à_remplir"
      - key: CLIENT_SECRET
        value: "à_remplir"
      - key: TENANT_ID
        value: "à_remplir"
